workflows:
  build_livecontainer_ipa:
    name: Build IPA (Development)
    environment:
      xcode: latest
      ios_signing:
        distribution_type: development
        bundle_identifier: com.hellocharlotte.heavensgate
    scripts:
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --project "HeavensGate.xcodeproj" \
            --scheme "HeavensGate"
    artifacts:
      - build/ios/ipa/*.ipa